[server]
headless = false
enableCORS = true
enableXsrfProtection = true
port = 8501
address = "localhost"

[theme]
base = "dark"
primaryColor = "#ff4c4c"
backgroundColor = "#0f0f0f"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff" 